name: astroventure
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  dotted_border: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: vt323
      fonts:
        - asset: assets/fonts/vt323.ttf

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  uses-material-design: true
